Разметка главной страницы
htmlacademy-adaptive/1837591-pink-24 pull request #2
Opened 2021-11-27 10:03 UTC by bitnik93

2021-11-27 12:34 UTC, summertime-fms requested changes

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +<html class="page" lang="ru">
Нет необходимости. Знаю, что в демке так, но подумай сам - у нас в корневом элементе только` head` и `body`.  Ну добавишь ты к `body` класс-элемент от блока `page`, но есть ли в этом необходимость?

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +    <header class="page-header">
Можно просто header, чтобы меньше писать потом)

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <div class="main-nav__list user-list">
Зачем доп обертка для ссылки?

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +            <img class="user-list__logo-image"></img>
Этому тегу классы не понадобятся. На этом курсе научися стилизовать картинки от обертки)

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
Перенеси спан на новую строчку чтобы было легче читать код.

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <div class="main-nav__wrapper">
Ненужная обертка

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +    <main class="page-main">
Нет необходимости, давай уберем

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +            <img class="wrapper__container" src="#">
Давай поступим немного хитрее и облегчим жизнь себе. Составь в фигме одну картинку из двух и экспортни.

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +          <div class="wrapper__phone">
Зачем обертка?)

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <div class="intro__links">
Зачем обертка? все идет  потоке одно под другим. Под картинкой кнопка, под кнопкой список ссылок на маркетплейсы

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +              <a class="intro__icon" href="#">iPhone</a>
в ТЗ прописано, что ссылки должны вести на маркетплейсы. Добавляем хрефы)

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +          <p class="intro__desc desc">Доступно для iPhone, iPad, Android, Windows Phone, OS X, Windows 8</p>
А зачем ты тут параграф текстовый вынес в отдельный блок?

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +          <ul class="info-list list-info">
выглядит сложно) можно запутаться. Я думаю этот блок не будет переиспользоваться поэтому список может спокойно жить как элемент от блока info. info__list вполне хватит

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +            <img class="wrapper-info__container" src="#">
Повторение истории с блоком intro.

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <div class="reviews__wrapper slider">
Вот тут хорошо. slider может переиспользоваться, да

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +              <button class="slider-toggle slider-toggle-current" type="button">1</button>
модификатор это когда два тире --

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +            <p class="reviews__toggles slider__toggle">
Параграф тут ка кто не особо уместен а вот див - да. перевесь классы на него с параграфа а сам параграф можно убрать

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +                <dd class="price_option"></dd>
Два нижних подеркивания вместо одного должно быть

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +      </section class="contacts">
Что это такое?)

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +          <h2 class="contacts__title">Остались вопросы? Свяжитесь с нами!</h2>
Скорее всего можно заголовки в отдельный блок выделить. типа `title contacts__title`. Первый будет отвечать за оформление а второй за позиционирование.

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +            <a class="contacts__html" href="#">mail@htmlacademy.ru</a>
протокол mailto нужен в хрефе

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +          <div class="contacts__phone">
я думаю тут уместно использовать` dl dd dt `

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +            <a class="contacts__adress" href="#">Ул. Большая конюшенная 19/8</a>
Есть семантический тег `address`

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +            <a class="contacts__adress" href="#">Ул. Большая конюшенная 19/8</a>
И это не ссылка мне кажетя

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +      <div class="page-footer__wrapper">
Нет необходимости) Можно центровать по классу page-footer.

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +      <div class="page-footer__wrapper">
И кстати давай лучше просто footer

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <div class="page-footer__list user-list">
Где тут список? Это ненужный див в принципе. Футер - лого - соцсети- копирайт. Все огчино одно за другим. Не нужны обертки

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <div class="page-footer__links">
список уместен

2021-11-27 12:34 UTC, summertime-fms commented on source/index.html
> +        <div class="copyright">
Кликабельный должен быть и текст и иконка (кажется, это есть в ТЗ). Поэтому давай обернем все в ссылку. Уберем спаны. Внутри будет текст + свг. Свг пока можешь не вставлять.

2021-11-28 10:05 UTC, bitnik93 commented on source/index.html
> +    <main class="page-main">
проверь пожалуйста, правильно ли я тебя понял

2021-11-28 10:08 UTC, bitnik93 commented on source/index.html
> +            <img class="wrapper__container" src="#">
картинка же в телефоне динамическая, на сколько я понял.
Я смотрел другие страницы, там меняется изображение в телефоне

2021-11-28 10:29 UTC, bitnik93 commented on source/index.html
> +      </section class="contacts">
это я угорел)

2021-11-29 08:38 UTC, summertime-fms requested changes

2021-11-29 08:38 UTC, summertime-fms commented on source/index.html
> +                <a class="contacts__html" href="#">mailto@htmlacademy.ru</a>
не так пишется. по аналогии с tel нужно https://htmlacademy.ru/blog/boost/frontend/mailto

2021-11-29 08:38 UTC, summertime-fms commented on source/index.html
> +                <adress class="contacts__adress" href="#">Ул. Большая конюшенная 19/8</adress>
опечатка. есть тег. address но не adress

2021-11-29 08:38 UTC, summertime-fms commented on source/index.html
> +                <adress class="contacts__adress" href="#">Ул. Большая конюшенная 19/8</adress>
и хреф забыл убрать

2021-11-29 08:38 UTC, summertime-fms commented on source/index.html
> +      <div class="user-list">
Зачем? Где тут список? Просто можно сразу пустить ссылку с лого. И ссылке надо бы еще класс зависимость от футера на всякий

2021-11-29 08:38 UTC, summertime-fms commented on source/index.html
> +      <div class="user-list">
Но основная проблема тут в названии класса. Это же не список это лого

2021-11-29 08:38 UTC, summertime-fms commented on source/index.html
> +        <li>
Это н е элемент соц сетей. Это отдельный блок футера.

2021-11-29 11:36 UTC, merged